workflows:
  meko-android:
    name: Meko Android

    environment:
      flutter: 3.43.2
      java: 17

    scripts:
      - name: Get packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
